services:
  astro:
    image: node:20
    working_dir: /app
    volumes:
      - ./frankuxui.dev:/app
    command: sh -c "npm install && npm run preview"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.astro.rule=Host(`frankuxui.dev`)"
      - "traefik.http.routers.astro.entrypoints=websecure"
      - "traefik.http.routers.astro.tls.certresolver=myresolver"
      - "traefik.http.services.astro.loadbalancer.server.port=4321"

networks:
  traefik:
    external: true
