services:
  strapi:
    image: strapi/strapi
    container_name: cms-frankuxui
    environment:
      - DATABASE_CLIENT=sqlite
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cms.rule=Host(`cms.frankuxui.dev`)"
      - "traefik.http.routers.cms.entrypoints=websecure"
      - "traefik.http.routers.cms.tls.certresolver=myresolver"
      - "traefik.http.services.cms.loadbalancer.server.port=1337"

networks:
  traefik:
    external: true
